repos:
-   repo: https://github.com/Czaki/absolufy-imports
    rev: v0.3.2-czaki
    hooks:
    -   id: absolufy-imports
        args: [--allow_local]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      exclude: _vendor|vendored|examples
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      pass_filenames: true
      exclude: _vendor|vendored|examples
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      additional_dependencies: [flake8-typing-imports]
      pass_filenames: true
      # this seems to need to be here in addition to setup.cfg
      exclude: _vendor|vendored|__init__.py|examples
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
    - id: pyupgrade
      args: ["--py38-plus", "--keep-runtime-typing"]
      exclude: _vendor|vendored|examples
-   repo: https://github.com/seddonym/import-linter
    rev: v1.4.0
    hooks:
    - id: import-linter
      stages: [manual]


