repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      exclude: _vendor|vendored|examples
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      pass_filenames: true
      exclude: _vendor|vendored|examples
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [flake8-typing-imports==1.11.0]
      pass_filenames: true
      # this seems to need to be here in addition to setup.cfg
      exclude: _vendor|vendored|__init__.py|examples
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade
      args: ["--py37-plus", "--keep-runtime-typing"]
      exclude: _vendor|vendored|examples
-   repo: https://github.com/seddonym/import-linter
    rev: v1.2.6
    hooks:
    - id: import-linter
      stages: [manual]


