exclude: _vendor|vendored
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.9
  hooks:
  - id: ruff-check
#    args:
#      - "--unsafe-fixes"
  - id: ruff-format
    exclude: examples
- repo: https://github.com/seddonym/import-linter
  rev: v2.9
  hooks:
  - id: import-linter
    stages: [manual]
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.35.0
  hooks:
  - id: check-github-workflows
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  # .py files are skipped cause already checked by other hooks
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: check-merge-conflict
    exclude: .*\.py
  - id: end-of-file-fixer
    exclude: .*\.py
  - id: trailing-whitespace
    # trailing whitespace has meaning in markdown https://www.markdownguide.org/hacks/#indent-tab
    exclude: .*\.py|.*\.md
  - id: mixed-line-ending
    exclude: .*\.py
- repo: local
  hooks:
  - id: check-groups-vs-extras
    name: check that all group names in pyproject.toml are in extras
    language: python
    entry: python tools/check_groups_vs_extras.py
    files: ^pyproject.toml$
