repos:
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    - id: pycln
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      pass_filenames: true
      exclude: _vendor|vendored|examples
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.262
    hooks:
      - id: ruff
        exclude: _vendor|vendored
-   repo: https://github.com/seddonym/import-linter
    rev: v1.8.0
    hooks:
    - id: import-linter
      stages: [manual]
-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-github-workflows
