exclude: _vendor|vendored
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.2
  hooks:
  - id: ruff-format
    exclude: examples
  - id: ruff
- repo: https://github.com/seddonym/import-linter
  rev: v2.1
  hooks:
  - id: import-linter
    stages: [manual]
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.31.0
  hooks:
  - id: check-github-workflows
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  # .py files are skipped cause already checked by other hooks
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: check-merge-conflict
    exclude: .*\.py
  - id: end-of-file-fixer
    exclude: .*\.py
  - id: trailing-whitespace
    # trailing whitespace has meaning in markdown https://www.markdownguide.org/hacks/#indent-tab
    exclude: .*\.py|.*\.md
  - id: mixed-line-ending
    exclude: .*\.py
