name: Benchmark Trigger by Label

on:
  pull_request:
    types: [labeled]

jobs:
  trigger-benchmarks:
    if: github.event.label.name == 'run-benchmarks'
    uses: ./.github/workflows/benchmarks.yml
    secrets: inherit
