name: Build PR Docs

on:
  push:
    branches:
      - docs
    tags:
      - 'v*'
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - '.github/workflows/build_docs.yml'
      - 'resources/constraints/*docs*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_docs:
    uses: napari/shared-workflows/.github/workflows/build_docs.yml@main
    secrets: inherit
    with:
      main-repo: ${{ github.repository }}
      main-ref: ${{ github.sha }}
      docs-repo: napari/docs
      docs-ref: main
      # Use slimfast to skip npe2 docs prep until npe2 has Pydantic V2 compatibility
      # Note: docs build may still fail due to Pydantic V2's model_json_schema
      # docstrings having formatting issues that Sphinx treats as errors.
      # This requires sphinx configuration changes in napari/docs repo.
      # See: https://github.com/napari/npe2/pull/419
      make_target: "slimfast"
