name: Build Docs

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-napari-docs:
    name: Build docs on napari/docs
    runs-on: ubuntu-latest
    steps:
      - name: get directory name
        # if this is a tag, use the tag name as the directory name else dev
        env:
          REF: ${{ github.ref }}
        run: |
          TAG="${GITHUB_REF/refs\/tags\/v/}"
          VER="${TAG/a*/}"  # remove alpha identifier
          VER="${VER/b*/}"  # remove beta identifier
          VER="${VER/rc*/}"  # remove rc identifier
          VER="${VER/post*/}"  # remove post identifier

          if [[ "$REF" == "refs/tags/v"* ]]; then
            echo "branch_name=$REF" >> "$GITHUB_ENV"
            echo "target_directory=$VER" >> "$GITHUB_ENV"
          else
            echo "branch_name=main" >> "$GITHUB_ENV"
            echo "target_directory=dev" >> "$GITHUB_ENV"
          fi
      - name: Trigger workflow and wait
        uses: convictional/trigger-workflow-and-wait@f69fa9eedd3c62a599220f4d5745230e237904be # v1.6.5
        with:
          owner: napari
          repo: docs
          github_token: ${{ secrets.ACTIONS_DEPLOY_DOCS }}
          workflow_file_name: build_and_deploy.yml
          trigger_workflow: true
          wait_workflow: true
          client_payload: '{"target_directory": "${{ env.target_directory }}", "napari_ref": "${{ env.branch_name }}", "docs_ref": "main"}'
