name: Clean up PR description

on:
  # see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_call:
# see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  pull-requests: write

jobs:
  check_labels:
    name: Remove html comments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: napari/napari
      # install python and requests
      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Remove html comments
        env:
          GH_PR_NUMBER: ${{ github.event.number }}
          GH_REPO_URL: ${{ github.event.repository.url}}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          python tools/remove_html_comments_from_pr.py
