name: Test translations

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  translations:
    name: Check missing translations
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python 3.11
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"
          cache-dependency-path: pyproject.toml
      - name: Install napari
        run: |
          pip install -e ".[all]"
          pip install -e ".[testing]"
      - name: Run check
        run: |
          python -m pytest -Wignore tools/ --tb=short
      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/missing_translations.md
          update_existing: true
